=== linked-art/shacl-validator/json-schema/digital.json
{
	"$schema": "http://json-schema.org/schema#",
	"$id": "file:///Users/rs2668/Development/other/linked-art/json-validator/schema/",
	"title": "Digital Object Schema",
	"description": "_dig:D1\\_Digital\\_Object_\nA digital resource, such as a web page or image.\nSee: [API](https://linked.art/api/1.0/endpoint/digital_object/) | [Model](https://linked.art/model/digital/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "DigitalObject"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of equivalent `DigitalObject` entities", 
				"type": "array", "items": {"$ref": "core.json#/definitions/DigitalObjectRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},
		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},

		"part_of": {"title": "crm:P106i_forms_part_of", "description": "Reference to another Digital Object of which this is part", "$ref": "core.json#/definitions/DigitalObjectRef"},
        "format": {"$ref": "core.json#/definitions/formatProp"},
		"conforms_to": {"$ref": "core.json#/definitions/conforms_toProp"},
		"access_point": {"$ref": "core.json#/definitions/access_pointProp"},
		"digitally_available_via": {"$ref": "core.json#/definitions/digitally_available_viaProp"},

		"digitally_carries": {"title": "la:digitally_carries", "description": "", "type": "array", "items": {"$ref": "core.json#/definitions/LinguisticObjectRef"}},
		"digitally_shows": {"title": "la:digitally_shows", "description": "", "type": "array", "items": {"$ref": "core.json#/definitions/VisualItemRef"}},
		"used_for": {"title": "crm:P16i_was_used_for", "description": "", "type": "array", "items": {"$ref": "core.json#/definitions/Activity"}},
		"created_by": {"title": "crm:P94i_was_created_by", "$ref": "#/definitions/Creation"}

	},
	"definitions": {
		"Creation": {
			"title": "crm:E65_Creation",
			"description": "The creation / writing of the digital object",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Creation"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this creation is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"}
			}
		}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/shacl-validator/la_examples/digital.1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/digital/1",
  "type": "DigitalObject",
  "_label": "Digital Object",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300264578",
      "type": "Type",
      "_label": "Web Page"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Informative Web Page"
    }
  ],
  "dimension": [
    {
      "type": "Dimension",
      "_label": "100 kb",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300265863",
          "type": "Type",
          "_label": "File Size"
        }
      ],
      "value": 100,
      "unit": {
        "id": "http://vocab.getty.edu/aat/300265870",
        "type": "MeasurementUnit",
        "_label": "kilobytes"
      }
    }
  ],
  "access_point": [
    {
      "id": "https://www.eg.museum/edu/page1.html",
      "type": "DigitalObject"
    }
  ],
  "format": "text/html",
  "conforms_to": [
    {
      "id": "http://w3.org/TR/html",
      "type": "InformationObject"
    }
  ],
  "created_by": {
    "type": "Creation",
    "timespan": {
      "type": "TimeSpan",
      "begin_of_the_begin": "2007-01-20T13:53:00Z",
      "end_of_the_end": "2007-01-20T13:54:00Z"
    },
    "carried_out_by": [
      {
        "type": "Group",
        "_label": "Museum Education Department"
      }
    ]
  }
}
