=== linked-art/shacl-validator/json-schema/object.json
{
	"$schema": "http://json-schema.org/schema#",
	"$id": "file:///Users/rs2668/Development/other/linked-art/json-validator/schema/",
	"title": "Human-Made Object Schema",
	"description": "_crm:E22\\_Human-Made\\_Object_\nA human-made object, part thereof, or a natural object with value imbued through interaction with human culture.\nSee: [API](https://linked.art/api/1.0/endpoint/object/) | [Model](https://linked.art/model/object/)",	
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "HumanMadeObject"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of `HumanMadeObject` entities", "type": "array", "items": {"$ref": "core.json#/definitions/HumanMadeObjectRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},

		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},
		"made_of": {"$ref": "core.json#/definitions/made_ofProp"},
                "part": {
                        "type": "array",
                        "items": {"$ref": "core.json#/definitions/HumanMadeObjectPart"}
                },
		"part_of": {"title": "crm:P46i_forms_part_of", "description": "Another Human-Made Object of which this Object is part", "$ref": "core.json#/definitions/HumanMadeObjectRef"},

		"current_owner": {"$ref": "core.json#/definitions/current_ownerProp"},
		"current_custodian": {"$ref": "core.json#/definitions/current_custodianProp"},
		"current_permanent_custodian": {"$ref": "core.json#/definitions/current_permanent_custodianProp"},
		"current_location": {"$ref": "core.json#/definitions/current_locationProp"},
		"used_for": {"$ref": "core.json#/definitions/used_forProp"},
		"shows": {"$ref": "core.json#/definitions/showsProp"},
		"carries": {"$ref": "core.json#/definitions/carriesProp"},

		"produced_by": {
			"title": "crm:P108i_was_produced_by",
			"description": "The `Production` activity which created this object",
			"$ref": "#/definitions/Production"},
		"destroyed_by": {
			"title": "crm:P13i_was_destroyed_by",
			"description": "The `Destruction` event in which this object was destroyed",
			"$ref": "#/definitions/Destruction"},
		"removed_by": {
			"title": "crm:P113i_was_removed_by",
			"description": "One or more `PartRemoval` activities in which this object was removed from another object",
			"type": "array", 
			"items": {"$ref": "#/definitions/PartRemoval"}}

	},

	"definitions": {
		"Production": {
			"title": "crm:E12_Production",
			"description": "The production/creation of the object",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Production"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},

				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this activity is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"},
				"part": {"title":"crm:P46_is_composed_of", "description": "", "type": "array", "items": {"$ref": "#/definitions/Production"}}
			}
		},
		"Destruction": {
			"title": "crm:E6_Destruction",
			"description": "The destruction of the object (separate from any cause of that end of existence)",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Destruction"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this event is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"}
			}
		},
		"PartRemoval": {
			"title": "crm:E80_Part_Removal",
			"description": "The activity of removing this object from some other object.",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "PartRemoval"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this activity is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"},
				"diminished": {"title": "crm:P112_diminished", "description": "A reference to the object which the object was removed from", "$ref": "core.json#/definitions/HumanMadeObjectRef"}
			}
		}				
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/shacl-validator/la_examples/object.20.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/20",
  "type": "HumanMadeObject",
  "_label": "Simple Example Painting",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting"
    },
    {
      "id": "http://vocab.getty.edu/aat/300133025",
      "type": "Type",
      "_label": "Work of Art"
    }
  ]
}

=== linked-art/shacl-validator/la_examples/object.30.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/30",
  "type": "HumanMadeObject",
  "_label": "Sculpture",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300047090",
      "type": "Type",
      "_label": "Sculpture",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    },
    {
      "id": "http://vocab.getty.edu/aat/300133025",
      "type": "Type",
      "_label": "Artwork"
    }
  ],
  "shows": [
    {
      "type": "VisualItem",
      "_label": "Visual content shown by sculpture",
      "digitally_shown_by": [
        {
          "type": "DigitalObject",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300215302",
              "type": "Type",
              "_label": "Digital Image"
            }
          ],
          "access_point": [
            {
              "id": "http://example.org/iiif/img/full/max/0/default.jpg",
              "type": "DigitalObject"
            }
          ],
          "digitally_available_via": [
            {
              "type": "DigitalService",
              "access_point": [
                {
                  "id": "http://example.org/iiif/img",
                  "type": "DigitalObject"
                }
              ],
              "conforms_to": [
                {
                  "id": "http://iiif.io/api/image",
                  "type": "InformationObject"
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/object.27.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/27",
  "type": "HumanMadeObject",
  "_label": "Painting",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    },
    {
      "id": "http://vocab.getty.edu/aat/300133025",
      "type": "Type",
      "_label": "Artwork"
    }
  ],
  "shows": [
    {
      "type": "VisualItem",
      "digitally_shown_by": [
        {
          "type": "DigitalObject",
          "_label": "Digitized Image of Painting",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300215302",
              "type": "Type",
              "_label": "Digital Image"
            }
          ],
          "format": "image/jpeg",
          "access_point": [
            {
              "id": "http://example.org/painting/image.jpg",
              "type": "DigitalObject"
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/object.13.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/13",
  "type": "HumanMadeObject",
  "_label": "Black and White Photograph of 'St. Sebastian'",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300128359",
      "type": "Type",
      "_label": "Black and White Photograph",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    }
  ],
  "member_of": [
    {
      "type": "Set",
      "_label": "Erwin Panofsky Collection",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300025976",
          "type": "Type",
          "_label": "Collection"
        }
      ]
    }
  ],
  "shows": [
    {
      "type": "VisualItem",
      "_label": "Image on Photograph",
      "represents": [
        {
          "type": "HumanMadeObject",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300033618",
              "type": "Type",
              "_label": "Painting",
              "classified_as": [
                {
                  "id": "http://vocab.getty.edu/aat/300435443",
                  "type": "Type",
                  "_label": "Type of Work"
                }
              ]
            },
            {
              "id": "http://vocab.getty.edu/aat/300133025",
              "type": "Type",
              "_label": "Artwork"
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/object.62.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/62",
  "type": "HumanMadeObject",
  "_label": "Paint sample",
  "removed_by": [
    {
      "type": "PartRemoval",
      "carried_out_by": [
        {
          "type": "Person",
          "_label": "Conservator"
        }
      ],
      "diminished": {
        "type": "HumanMadeObject",
        "_label": "Painting",
        "classified_as": [
          {
            "id": "http://vocab.getty.edu/aat/300033618",
            "type": "Type",
            "_label": "Painting",
            "classified_as": [
              {
                "id": "http://vocab.getty.edu/aat/300435443",
                "type": "Type",
                "_label": "Type of Work"
              }
            ]
          }
        ]
      }
    }
  ]
}

=== linked-art/shacl-validator/la_examples/object.14.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/14",
  "type": "HumanMadeObject",
  "_label": "St. Sebastian",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    },
    {
      "id": "http://vocab.getty.edu/aat/300133025",
      "type": "Type",
      "_label": "Artwork"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "St. Sebastian"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435429",
          "type": "Type",
          "_label": "Material Statement",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Oil on canvas"
    }
  ],
  "dimension": [
    {
      "type": "Dimension",
      "_label": "Height",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300055644",
          "type": "Type",
          "_label": "Height"
        }
      ],
      "value": 153,
      "unit": {
        "id": "http://vocab.getty.edu/aat/300379098",
        "type": "MeasurementUnit",
        "_label": "centimeters"
      }
    },
    {
      "type": "Dimension",
      "_label": "Width",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300055647",
          "type": "Type",
          "_label": "Width"
        }
      ],
      "value": 118,
      "unit": {
        "id": "http://vocab.getty.edu/aat/300379098",
        "type": "MeasurementUnit",
        "_label": "centimeters"
      }
    }
  ],
  "made_of": [
    {
      "id": "http://vocab.getty.edu/aat/300015050",
      "type": "Material",
      "_label": "oil"
    }
  ],
  "part": [
    {
      "type": "HumanMadeObject",
      "_label": "Canvas Support",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300014844",
          "type": "Type",
          "_label": "Support",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300241583",
              "type": "Type",
              "_label": "Part Type"
            }
          ]
        }
      ],
      "made_of": [
        {
          "id": "http://vocab.getty.edu/aat/300014078",
          "type": "Material",
          "_label": "canvas"
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/object.56.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/object/56",
  "type": "HumanMadeObject",
  "_label": "Graffiti",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300133025",
      "type": "Type",
      "_label": "Artwork"
    }
  ],
  "produced_by": {
    "type": "Production",
    "_label": "Production of Graffiti",
    "classified_as": [
      {
        "id": "http://vocab.getty.edu/aat/300055299",
        "type": "Type",
        "_label": "Vandalism"
      }
    ],
    "technique": [
      {
        "id": "http://vocab.getty.edu/aat/300053816",
        "type": "Type",
        "_label": "Spraypainting"
      }
    ]
  }
}

=== linked-art/shacl-validator/data/example_object.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/testshacl/object/t0",
  "type": "HumanMadeObject",
  "_label": "t0",
  "produced_by": {

    "diminished": {
        "id": "https://linked.art/testshacl/object/t0_diminished",
        "type": "HumanMadeObject",
        "_label": "Painting",
        "classified_as": [
          {
            "id": "http://vocab.getty.edu/aat/300033618",
            "type": "Type",
            "_label": "Painting",
            "classified_as": [
              {
                "id": "http://vocab.getty.edu/aat/300435443",
                "type": "Type",
                "_label": "Type of Work"
              }
            ]
          }
        ]
    },

    "technique": [
      {
        "id": "http://vocab.getty.edu/aat/300053932",
        "type": "Type",
        "_label": "Glassblowing"
      }
    ],

    "used_specific_object": [{
        "type": "HumanMadeObject",
        "_label": "Negative of Photograph",
        "classified_as": [
          {
            "id": "http://vocab.getty.edu/aat/300127173",
            "type": "Type",
            "_label": "Photographic Negative",
            "classified_as": [
              {
                "id": "http://vocab.getty.edu/aat/300435443",
                "type": "Type",
                "_label": "Type of Work"
              }
            ]
          }
        ],
        "shows": [
          {
            "type": "VisualItem",
            "_label": "Visual Content of Photographs and Negative"
          }
        ]
    }],

    "influenced_by": [{
        "type": "Person",
        "_label": "Well Known Artist"
    }],

    "carried_out_by": [{
        "type": "Person",
        "_label": "Well Known Artist"
    }],
    "caused_by": [
      {
        "type": "Activity",
        "_label": "Burning of the Painting",
        "carried_out_by": [
          {
            "type": "Person",
            "_label": "Painting Burner"
          }
        ]
      }
    ],
    "_label" : "a label",
    "type": "Production",
    "timespan": {
      "_label" : "a label",
      "type": "TimeSpan",
      "identified_by": [
          {
            "type": "Name",
            "classified_as": [{
                "id": "http://vocab.getty.edu/aat/300404669",
                "type": "Type",
                "_label": "Display Title"
            }],
            "content": "1503-1506"
          },
          {
            "type": "Name",
            "classified_as": [{
                "id": "http://vocab.getty.edu/aat/300404670",
                "type": "Type",
                "_label": "Primary Name"
            }],
            "content": "This portrait was doubtless started in Florence around 1503. It is thought to be of Lisa Gherardini, wife of a Florentine cloth merchant ...",
            "language": [{
                "id": "http://vocab.getty.edu/aat/300388306",
                "type": "Language",
                "_label": "French"
            }]
          }
      ],
      "classified_as": [{
        "id": "http://vocab.getty.edu/aat/300033618",
        "type": "Type",
        "_label": "Painting"
      }],
      "begin_of_the_begin": "1503-01-01T00:00:00Z",
      "end_of_the_end": "1506-12-31T23:59:59Z"
    },
    "took_place_at": [{
        "id": "http://vocab.getty.edu/tgn/7000457",
        "type": "Place",
        "_label": "Florence, Italy"
    }],
    "carried_out_by": [{
        "id": "http://vocab.getty.edu/ulan/500010879",
        "type": "Person",
        "_label": "Leonardo da Vinci"
    }],
    "classified_as": [{
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting"
    }],
    "identified_by": [{
        "type": "Name",
        "classified_as": [{
            "id": "http://vocab.getty.edu/aat/300404670",
            "type": "Type",
            "_label": "Primary Name"
        }],
        "content": "This portrait was doubtless started in Florence around 1503. It is thought to be of Lisa Gherardini, wife of a Florentine cloth merchant ...",
        "language": [{
            "id": "http://vocab.getty.edu/aat/300388306",
            "type": "Language",
            "_label": "French"
        }]
    }]
  },
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300033618",
      "type": "Type",
      "_label": "Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435443",
          "type": "Type",
          "_label": "Type of Work"
        }
      ]
    },
    {
      "id": "http://vocab.getty.edu/aat/300133025",
      "type": "Type",
      "_label": "Artwork"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        },
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "This portrait was doubtless started in Florence around 1503. It is thought to be of Lisa Gherardini, wife of a Florentine cloth merchant ...",
      "language": [
        {
          "id": "http://vocab.getty.edu/aat/300388306",
          "type": "Language",
          "_label": "French"
        }
      ]
    },
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300312355",
          "type": "Type",
          "_label": "Accession Number"
        }
      ],
      "content": "INV. 779"
    }
  ]
}
