=== linked-art/shacl-validator/json-schema/person.json
{
	"$schema": "http://json-schema.org/schema#",
	"$id": "file:///Users/rs2668/Development/other/linked-art/json-validator/schema/",
	"title": "Person Schema",
	"description": "_crm:E21\\_Person_\nA human.\nSee: [API](https://linked.art/api/1.0/endpoint/person/) | [Model](https://linked.art/model/actor/)",	
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "Person"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of `Person` entities", "type": "array", "items": {"$ref": "core.json#/definitions/PersonRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofGroupProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},

		"carried_out": {"$ref": "core.json#/definitions/carried_outProp"},
		"contact_point": {"$ref": "core.json#/definitions/contact_pointProp"},
		"residence": {"$ref": "core.json#/definitions/residenceProp"},

		"born": {
			"title": "crm:P98i_was_born",
			"description": "The event in which this Person was born", 
			"$ref": "#/definitions/Birth"
		},
		"died": {
			"title": "crm:P100i_died_in",
			"description": "The event in which this Person died",
			"$ref": "#/definitions/Death"
		}
	},
	"definitions": {
		"Birth": {
			"title": "crm:E67_Birth",
			"description": "The birth event of a person",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Birth"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"}
			}
		},
		"Death": {
			"title": "crm:E69_Death", 
			"description": "The death event of a person",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Death"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"}
			}
		}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/shacl-validator/la_examples/person.9.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/9",
  "type": "Person",
  "_label": "Patrick Q. Robertson",
  "carried_out": [
    {
      "type": "Activity",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300393177",
          "type": "Type",
          "_label": "Professional Activities"
        }
      ],
      "timespan": {
        "type": "TimeSpan",
        "begin_of_the_begin": "1910-01-01",
        "end_of_the_end": "1934-03-21"
      }
    }
  ]
}

=== linked-art/shacl-validator/la_examples/person.5.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/5",
  "type": "Person",
  "_label": "Xavier Y. Zeelander",
  "identified_by": [
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404621",
          "type": "Type",
          "_label": "Owner-Assigned Number"
        }
      ],
      "content": "643"
    }
  ]
}

=== linked-art/shacl-validator/la_examples/person.11.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/11",
  "type": "Person",
  "_label": "Jeremy K. Lintott",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300111159",
      "type": "Type",
      "_label": "British",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300379842",
          "type": "Type",
          "_label": "Nationality"
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/person.12.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/12",
  "type": "Person",
  "_label": "Mabel N. Overton",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300189557",
      "type": "Type",
      "_label": "Feminine",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300055147",
          "type": "Type",
          "_label": "Gender"
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/person.10.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/10",
  "type": "Person",
  "_label": "David E. Frederickson",
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435422",
          "type": "Type",
          "_label": "Biography Statement",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "David was born at a very early age."
    }
  ]
}
