=== linked-art/shacl-validator/json-schema/person.json
{
	"$schema": "http://json-schema.org/schema#",
	"$id": "file:///Users/rs2668/Development/other/linked-art/json-validator/schema/",
	"title": "Person Schema",
	"description": "_crm:E21\\_Person_\nA human.\nSee: [API](https://linked.art/api/1.0/endpoint/person/) | [Model](https://linked.art/model/actor/)",	
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "Person"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of `Person` entities", "type": "array", "items": {"$ref": "core.json#/definitions/PersonRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofGroupProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},

		"carried_out": {"$ref": "core.json#/definitions/carried_outProp"},
		"contact_point": {"$ref": "core.json#/definitions/contact_pointProp"},
		"residence": {"$ref": "core.json#/definitions/residenceProp"},

		"born": {
			"title": "crm:P98i_was_born",
			"description": "The event in which this Person was born", 
			"$ref": "#/definitions/Birth"
		},
		"died": {
			"title": "crm:P100i_died_in",
			"description": "The event in which this Person died",
			"$ref": "#/definitions/Death"
		}
	},
	"definitions": {
		"Birth": {
			"title": "crm:E67_Birth",
			"description": "The birth event of a person",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Birth"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"}
			}
		},
		"Death": {
			"title": "crm:E69_Death", 
			"description": "The death event of a person",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Death"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"}
			}
		}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/shacl-validator/la_examples/person.8.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/8",
  "type": "Person",
  "_label": "Amanda B. Curtlett",
  "born": {
    "type": "Birth",
    "timespan": {
      "type": "TimeSpan",
      "begin_of_the_begin": "1767-01-09",
      "end_of_the_end": "1767-01-12"
    }
  },
  "died": {
    "type": "Death",
    "timespan": {
      "type": "TimeSpan",
      "begin_of_the_begin": "1824-08-21",
      "end_of_the_end": "1824-08-21"
    },
    "took_place_at": [
      {
        "type": "Place",
        "_label": "Death Place"
      }
    ]
  }
}

=== linked-art/shacl-validator/la_examples/person.7.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/7",
  "type": "Person",
  "_label": "A. Bacchus",
  "member_of": [
    {
      "type": "Group",
      "_label": "Example City Museum",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300312281",
          "type": "Type",
          "_label": "Museum"
        }
      ],
      "contact_point": [
        {
          "type": "Identifier",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300386983",
              "type": "Type",
              "_label": "Street Address"
            }
          ],
          "content": "1200 Museum Drive, Example City"
        }
      ]
    }
  ],
  "contact_point": [
    {
      "type": "Identifier",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435686",
          "type": "Type",
          "_label": "Email Address"
        }
      ],
      "content": "a.person@example.org"
    }
  ]
}

=== linked-art/shacl-validator/la_examples/person.13.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/13",
  "type": "Person",
  "_label": "Gertrude H. Ingram",
  "representation": [
    {
      "type": "VisualItem",
      "digitally_shown_by": [
        {
          "id": "http://example.org/images/gertrude.jpg",
          "type": "DigitalObject",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300215302",
              "type": "Type",
              "_label": "Digital Image"
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/person.14.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/14",
  "type": "Person",
  "_label": "Sameen T. Underwood",
  "member_of": [
    {
      "type": "Group",
      "_label": "Paintings Department",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300263534",
          "type": "Type",
          "_label": "Department"
        }
      ],
      "member_of": [
        {
          "type": "Group",
          "_label": "Example Museum",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300312281",
              "type": "Type",
              "_label": "Museum"
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/person.6.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/6",
  "type": "Person",
  "_label": "Vincent Van Gogh",
  "equivalent": [
    {
      "id": "http://vocab.getty.edu/ulan/500115588",
      "type": "Person",
      "_label": "Vincent Van Gogh"
    }
  ]
}

=== linked-art/shacl-validator/la_examples/person.4.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/4",
  "type": "Person",
  "_label": "Joan A. Smith",
  "identified_by": [
    {
      "type": "Name",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300404670",
          "type": "Type",
          "_label": "Primary Name"
        }
      ],
      "content": "Joan A. Smith",
      "part": [
        {
          "type": "Name",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300404651",
              "type": "Type",
              "_label": "Given Name"
            }
          ],
          "content": "Joan"
        },
        {
          "type": "Name",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300404654",
              "type": "Type",
              "_label": "Middle Name"
            }
          ],
          "content": "A."
        },
        {
          "type": "Name",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300404652",
              "type": "Type",
              "_label": "Family Name"
            }
          ],
          "content": "Smith"
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/person.15.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/15",
  "type": "Person",
  "_label": "E.G. Person",
  "representation": [
    {
      "type": "VisualItem",
      "digitally_shown_by": [
        {
          "type": "DigitalObject",
          "_label": "Image of Person",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300215302",
              "type": "Type",
              "_label": "Digital Image"
            }
          ],
          "format": "image/jpeg",
          "access_point": [
            {
              "id": "http://example.org/egperson/image.jpg",
              "type": "DigitalObject"
            }
          ]
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/person.2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/person/2",
  "type": "Person",
  "_label": "J. Smith",
  "member_of": [
    {
      "type": "Group",
      "_label": "Museum Organization",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300312281",
          "type": "Type",
          "_label": "Museum"
        }
      ]
    }
  ]
}
