=== linked-art/shacl-validator/json-schema/place.json
{
	"$schema": "http://json-schema.org/schema#",
	"$id": "file:///Users/rs2668/Development/other/linked-art/json-validator/schema/",
	"title": "Place Schema",
	"description": "_crm:E53\\_Place_\nGeographic locations where activities occur.\nSee: [API](https://linked.art/api/1.0/endpoint/place/) | [Model](https://linked.art/model/place/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "Place"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of `Place` entities", "type": "array", "items": {"$ref": "core.json#/definitions/PlaceRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},

		"defined_by": {
			"title": "crm:P168_place_is_defined_by",
			"description": "A string with a WKT or GeoJSON definition of the area of the Place",
			"type": "string"

		},
		"approximated_by": {
			"title": "crm:P189i_is_approximated_by",
			"description": "This `Place` is approximately the same area as the given entities",  
			"type": "array", 
			"items": {"$ref": "core.json#/definitions/PlaceRef"}
		},
		"part_of": {
			"title": "crm:P89_falls_within",
			"description": "This `Place` is contained within one or more larger `Place` entities",
			"type": "array", 
			"items": {"$ref": "core.json#/definitions/PlaceRef"}
		}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/shacl-validator/la_examples/place.4.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/place/4",
  "type": "Place",
  "_label": "True Auction House Location",
  "approximated_by": [
    {
      "type": "Place",
      "_label": "Auction House Location Approximation",
      "defined_by": "POINT(-0.0032937526703165 51.515107154846)"
    }
  ]
}

=== linked-art/shacl-validator/la_examples/place.2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/place/2",
  "type": "Place",
  "_label": "Los Angeles, CA",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300008389",
      "type": "Type",
      "_label": "City"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Los Angeles"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435416",
          "type": "Type",
          "_label": "Description",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "Los Angeles is a city in California, USA."
    }
  ],
  "part_of": [
    {
      "type": "Place",
      "_label": "California",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300000774",
          "type": "Type",
          "_label": "Province"
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/place.1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/place/1",
  "type": "Place",
  "_label": "Rome",
  "part_of": [
    {
      "type": "Place",
      "_label": "Roma",
      "part_of": [
        {
          "type": "Place",
          "_label": "Lazio",
          "part_of": [
            {
              "type": "Place",
              "_label": "Italy"
            }
          ]
        }
      ]
    }
  ]
}
