=== linked-art/shacl-validator/json-schema/text.json
{
	"$schema": "http://json-schema.org/schema#",
	"$id": "file:///Users/rs2668/Development/other/linked-art/json-validator/schema/",
	"title": "Text Schema",
	"description": "_crm:E33\\_Linguistic\\_Object_\nTextual content expressed in one or more human languages, which might or might not be written down on any physical carrier.\nSee: [API](https://linked.art/api/1.0/endpoint/textual_work/) | [Model](https://linked.art/model/document/)",
	"type": "object",
	"properties": {
		"@context": {"$ref": "core.json#/definitions/ContextStringOrArray"},
		"id": {"$ref": "core.json#/definitions/idProp"},				
		"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
			{"title": "Specific", "type": "string", "const": "LinguisticObject"}]},
		"_label": {"$ref": "core.json#/definitions/labelProp"},
		"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
		"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
		"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
		"equivalent": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/equivalentProp"}, 
			{"title": "Specific", "description": "List of equivalent `LinguisticObject` entities", "type": "array", "items": {"$ref": "core.json#/definitions/LinguisticObjectRef"}}]},
		"representation": {"$ref": "core.json#/definitions/representationProp"},
		"member_of": {"$ref": "core.json#/definitions/member_ofSetProp"},
		"subject_of": {"$ref": "core.json#/definitions/subject_ofProp"},
		"attributed_by": {"$ref": "core.json#/definitions/attributed_byRelProp"},
		"dimension": {"$ref": "core.json#/definitions/dimensionProp"},

		"part_of": {"title": "crm:P106i_forms_part_of", "description": "Reference to another Linguistic Object of which this is part", "$ref": "core.json#/definitions/LinguisticObjectRef"},
        "content": {"$ref": "core.json#/definitions/contentProp"},
        "format": {"$ref": "core.json#/definitions/formatProp"},
		"language": {"$ref": "core.json#/definitions/languageProp"},

		"digitally_carried_by": {"title": "la:digitally_carried_by", "description": "", "type": "array", "items": {"$ref": "core.json#/definitions/DigitalObjectRef"}},
		"carried_by": {"title": "crm:P128i_is_carried_by", "description": "", "type": "array", "items": {"$ref": "core.json#/definitions/HumanMadeObjectRef"}},
		"about": {"title": "crm:P129_is_about", "description": "The main topic(s) of the content", "type": "array", "items": {"$ref": "core.json#/definitions/AnyRef"}},
		"refers_to": {"title": "crm:P67_refers_to", "description": "Entities referred to by the content, but are not the main topic", "type": "array", "items": {"$ref": "core.json#/definitions/AnyRef"}},
		"created_by": {"title": "crm:P94i_was_created_by", "$ref": "#/definitions/Creation"},
		"used_for": {"title": "crm:P16i_was_used_for", "description": "", "type": "array", "items": {"$ref": "core.json#/definitions/Activity"}}

	},
	"definitions": {
		"Creation": {
			"title": "crm:E65_Creation",
			"description": "The creation / writing of the text",
			"type": "object",
			"properties": {
				"type": {"allOf": [{"title": "General", "$ref": "core.json#/definitions/typeProp"}, 
					{"title": "Specific", "type": "string", "const": "Creation"}]},
				"_label": {"$ref": "core.json#/definitions/labelProp"},
				"identified_by": {"$ref": "core.json#/definitions/identified_byProp"},
				"classified_as": {"$ref": "core.json#/definitions/classified_asProp"},
				"referred_to_by": {"$ref": "core.json#/definitions/referred_to_byProp"},
				"took_place_at": {"$ref": "core.json#/definitions/took_place_atProp"},
				"timespan": {"$ref": "core.json#/definitions/timespanProp"},
				"caused_by": {"$ref": "core.json#/definitions/caused_byProp"},
				"carried_out_by": {"$ref": "core.json#/definitions/carried_out_byProp"},
				"used_specific_object": {"$ref": "core.json#/definitions/used_specific_objectProp"},
				"influenced_by": {"$ref": "core.json#/definitions/influenced_byProp"},
				"technique": {"$ref": "core.json#/definitions/techniqueProp"},
				"part_of": {"title": "crm:P9i_forms_part_of", "description": "An identified event or activity which this creation is part of", "$ref": "core.json#/definitions/EventRefOrActivityRef"}
			}
		}
	},
	"required": ["@context", "id", "type", "_label"],
	"additionalProperties": false
}

=== linked-art/shacl-validator/la_examples/text.2.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/2",
  "type": "LinguisticObject",
  "_label": "Example Journal Article",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300048715",
      "type": "Type",
      "_label": "Article"
    }
  ],
  "created_by": {
    "type": "Creation",
    "_label": "Creation of the Article Content",
    "carried_out_by": [
      {
        "type": "Person",
        "_label": "Author"
      }
    ]
  },
  "used_for": [
    {
      "type": "Activity",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300054686",
          "type": "Type",
          "_label": "Publishing"
        }
      ],
      "carried_out_by": [
        {
          "type": "Group",
          "_label": "Publishing House"
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/text.4.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/4",
  "type": "LinguisticObject",
  "_label": "Example 10 page Article",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300048715",
      "type": "Type",
      "_label": "Article"
    }
  ],
  "referred_to_by": [
    {
      "type": "LinguisticObject",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300435440",
          "type": "Type",
          "_label": "Pagination Statement",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300418049",
              "type": "Type",
              "_label": "Brief Text"
            }
          ]
        }
      ],
      "content": "125-135"
    }
  ]
}

=== linked-art/shacl-validator/la_examples/text.6.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/6",
  "type": "LinguisticObject",
  "_label": "Article about Example Painting",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300048715",
      "type": "Type",
      "_label": "Article"
    }
  ],
  "refers_to": [
    {
      "type": "HumanMadeObject",
      "_label": "Example Painting",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300033618",
          "type": "Type",
          "_label": "Painting",
          "classified_as": [
            {
              "id": "http://vocab.getty.edu/aat/300435443",
              "type": "Type",
              "_label": "Type of Work"
            }
          ]
        },
        {
          "id": "http://vocab.getty.edu/aat/300133025",
          "type": "Type",
          "_label": "Artwork"
        }
      ]
    }
  ]
}

=== linked-art/shacl-validator/la_examples/text.1.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/1",
  "type": "LinguisticObject",
  "_label": "Example Article",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300048715",
      "type": "Type",
      "_label": "Article"
    }
  ],
  "identified_by": [
    {
      "type": "Name",
      "content": "Title of Article"
    },
    {
      "type": "Identifier",
      "_label": "DOI of Article",
      "content": "10.1000/1011"
    }
  ],
  "language": [
    {
      "id": "http://vocab.getty.edu/aat/300388277",
      "type": "Language",
      "_label": "English"
    }
  ]
}

=== linked-art/shacl-validator/la_examples/text.5.json
{
  "@context": "https://linked.art/ns/v1/linked-art.json",
  "id": "https://linked.art/example/text/5",
  "type": "LinguisticObject",
  "_label": "Abstract of Example Article",
  "classified_as": [
    {
      "id": "http://vocab.getty.edu/aat/300026032",
      "type": "Type",
      "_label": "Abstract",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300418049",
          "type": "Type",
          "_label": "Brief Text"
        }
      ]
    }
  ],
  "content": "This is the abstract of the example article, which is excellent.",
  "refers_to": [
    {
      "type": "LinguisticObject",
      "_label": "Example Article",
      "classified_as": [
        {
          "id": "http://vocab.getty.edu/aat/300048715",
          "type": "Type",
          "_label": "Article"
        }
      ]
    }
  ],
  "created_by": {
    "type": "Creation",
    "carried_out_by": [
      {
        "type": "Person",
        "_label": "Example Abstracter"
      }
    ]
  }
}
